spring:
  cloud:
    openfeign:
      client:
        config:
# default是默认配置，对所有@FeignClient配置的feign类生效
          default:
            loggerLevel: full
            connectTimeout: 1000
            readTimeout: 3000
# service-product的名称是@FeignClient注解中的contextId,没有则是value值
          service-product:
            loggerLevel: full
#            请求超时时间，单位毫秒
            connectTimeout: 3000
#            读取超时时间，单位毫秒
            readTimeout: 5000
#            retryer: feign.Retryer.Default
#            自定义请求拦截器
#            request-interceptors:
#              - com.zhao.order.interceptor.XTokenRequestInterceptor

#  服务保护（限流熔断）
    sentinel:
      transport:
        dashboard: localhost:8080
      eager: true
#      开启 Web 上下文统一, 默认为 false, 开启后, 会将 Web 请求的上下文信息统一到 Sentinel 中, 方便在 Sentinel 中进行上下文的传递
#      Sentinel链路
#      web-context-unify: false


feign:
#  服务熔断
  sentinel:
#    开启 Sentinel 对 Feign 客户端的支持, 默认为 false, 开启后, 会对 Feign 客户端的调用进行限流和降级
    enabled: true