spring:
  cloud:
    openfeign:
      client:
        config:
# default是默认配置，对所有@FeignClient配置的feign类生效
          default:
            loggerLevel: full
            connectTimeout: 1000
            readTimeout: 3000
# service-product的名称是@FeignClient注解中的contextId,没有则是value值
          service-product:
            loggerLevel: full
#            请求超时时间，单位毫秒
            connectTimeout: 3000
#            读取超时时间，单位毫秒
            readTimeout: 5000
#            retryer: feign.Retryer.Default
